project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  navbar:
    background: light
    theme: light
    left: 
      - href: index.qmd
        text: Home
      - href: /#research
        text: Research
      - href: /#teaching
        text: Teaching
      - href: cv.qmd
        text: CV
        

format:
  html:
    theme: default
    data-bs-theme: dark
    css: styles.css
    toc: true

editor: visual

