# _quarto.yml
project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  favicon: assets/logo-transparent-png.png
  navbar:
    title: "Md Twfiqur Rahman"
    right: 
      - href: "#about"
        text: About
      - href: "#research"
        text: Research
      - href: "#teaching"
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: resources.qmd
        text: Resources
      - icon: github
        href: https://github.com/tofurahman/tofurahman.github.io

format:
  html:
    theme:
      light: litera
      dark: slate
    css: styles.css
    toc: false