project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  navbar:
    background: dark
    theme: dark
    right: 
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
        

format:
  html:
    theme: Lumen
    data-bs-theme: dark
    css: styles.css
    toc: true

editor: visual

