project:
  type: website
  output-dir: docs

website:
  title: "M. T. Rahman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

