project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  navbar:
    background: light
    theme: light
    right: 
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: /#research
        text: Research
      - href: /#teaching
        text: teaching
        

format:
  html:
    theme: Cosmo
    data-bs-theme: light
    css: styles.css
    toc: true

editor: visual

