# _quarto.yml

project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  favicon: assets/logo-transparent-png.png
  
# The navbar: section has been completely removed.

format:
  html:
    theme: flatly
    css: styles.css
    mainfont: "Lato"
    sansfont: "Lato"
    template: _layout.html