project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  favicon: assets/logonobg.png
  navbar:
    title: false
    logo: assets/logonobg.png
    logo-alt: "Md Twfiqur Rahman"
    background: light
    theme: light
    right: 
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/tofurahman/tofurahman.github.io
          - text: Report an issue
            href: mailto:mrahman24@gsu.edu


format:
  html:
    theme: default
    data-bs-theme: dark
    css: styles.css
    toc: true

editor: visual

