project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  navbar: 
    right: 
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: CV
        

format:
  html:
    theme: flatly
    data-bs-theme: light
    css: styles.css
    toc: true

editor: visual

