project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman"
  navbar:
    background: light
    theme: light
    right: 
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/tofurahman/tofurahman.github.io

        

format:
  html:
    theme: default
    data-bs-theme: dark
    css: styles.css
    toc: true

editor: visual

