# _quarto.yml
project:
  type: website
  output-dir: docs

website:
  title: "Md Twfiqur Rahman" # This will now appear in the navbar
  favicon: assets/logo-transparent-png.png
  navbar:
    title: "Md Twfiqur Rahman" # Use the title field for your name
    # We remove the logo keys since your name is the title now
    right: 
      - href: "#about"
        text: About
      - href: "#research"
        text: Research
      - href: "#teaching"
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: resources.qmd
        text: Resources
      - icon: github
        href: https://github.com/tofurahman/tofurahman.github.io

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false