### **WORKING PAPERS**

<hr style="border:2px solid gray">

<details>

<summary>Effects of Losing Medicaid on Body Weight and Health Behaviors <font color=blue; size="2"><i>(Job Market Paper)</i></font></summary>

Approximately 170,000 childless adults abruptly lost Medicaid coverage as a result of Tennessee's 2005 Medicaid reform. Leveraging this policy-induced variation in health insurance coverage, I investigate the impact of large-scale Medicaid disenrollment on body weight and health behaviors. Using Behavioral Risk Factor Surveillance System (BRFSS) data from 1997 to 2010, I estimate synthetic difference-in-differences models that compare Tennessee's outcomes before and after the reform with those of a data-driven, synthetic Tennessee. The findings indicate that the reform increased Body Mass Index (BMI) among Tennessean childless adults by 0.37 points, contributing to roughly 4% rise in the prevalence of overweight or obese individuals (BMI≥25). The effects are strong among young (aged 20-39) as well as female childless adults, who likely experienced disproportionately large coverage loss due to the reform. Examining potential mechanisms, I find that decreased participation in moderate physical activity (e.g., cycling, swimming) and dietary changes partially explain the weight gain.

</details>

<details>

<summary>The Effects of AP Exam Fee Waivers: Evidence from North Carolina <font size="2">(with Cade Lawsom and Salma Ali)</font></summary>

To be updated soon.

</details>

<br>

### **WORK IN PROGRESS**

<hr style="border:2px solid gray">

<details>

<summary>Incentive Strength and Teacher Effort: New Evidence from Piece-rate Bonus Scheme</summary>

</details>

<details>

<summary>Eviction in the Gig Economy: The Uber Effect</summary>

</details>
