---
title: "Too Long; Didn't Read version for"
mainfont: Lato
---

### The Effects of Losing Medicaid on Body Weight and Health Behaviors

#### **WHY?**

While prior research documented the effects of gaining Medicaid coverage on Body Mass Index (BMI) and related health behaviors and led to diverging conclusions, there is a notable gap in understanding the effects of losing Medicaid.

#### **HOW?**

I exploit variation in health insurance coverage induced by Tennessee's 2005 Medicaid reform, which abruptly terminated health insurance coverage for approximately 4% (170,000) of Tennessee's childless adults.

Using BRFSS data from 1997 to 2010, I estimate comparative case study models that compare Tennessee's pre- and post-reform outcomes to those of data-driven control groups'. Specifically, for body weight outcomes, I estimates difference-in-differences, synthetic difference-in-differences, and synthetic control methods.

#### **WHAT?**

The results of my pre

I find that following

Contributions:

The use of SDiD in the Tennessee's setting addresses two potential problems in the analysis of single treated clusters.

1.  Standard DiD methods may severely understate the standard errors.
2.  The bias from nonparallel evolution of outcomes between the treated and control states may result in severely overstating a given effect.

I provide empirical evidence to highlight these problems by re-examining the estimates of a few prior studies.
